export const FETCH_PRODUCTS_FROM_SERVER = 'FETCH_PRODUCTS_FROM_SERVER';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const USER_EXIST = 'USER_EXIST';
export const SEARCH_PRODUCT_IN_DB = 'SEARCH_PRODUCT_IN_DB';
export const SEARCH_BY_PRICE = 'SEARCH_BY_PRICE';