export const FETCH_PRODUCTS_FROM_SERVER = 'FETCH_PRODUCTS_FROM_SERVER';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const USER_EXIST = 'USER_EXIST';
export const USER_EMAIL = 'USER_EMAIL';
export const SEARCH_PRODUCT_IN_DB = 'SEARCH_PRODUCT_IN_DB';
export const SEARCH_BY_PRICE = 'SEARCH_BY_PRICE';
export const SEARCH_BY_PRICE_MORE = 'SEARCH_BY_PRICE_MORE';
export const FETCH_LAST_15_PRODUCTS_FROM_DB = 'FETCH_LAST_15_PRODUCTS_FROM_DB';
export const MESSAGE_COUNTER = 'MESSAGE_COUNTER';
export const USER_PAYMENT_SETTINGS = 'USER_PAYMENT_SETTINGS';
export const USER_PERSONAL_DETAILS = 'USER_PERSONAL_DETAILS';
export const SHOPCART_PRODUCT_COUNTER = 'SHOPCART_PRODUCT_COUNTER';


